### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DaGnYMilleR** [lapakota/try_cach#1]
What about writing telegram bot for your app?
Because me and my friends have an iPhone. But we really want to use your app in the gym

**Comment by lapakota** [comment]
Great idea, but unfortunately there are too few people on our team to accomplish this task, sorry

**Comment by IvanSibirtsev** [comment]
You can do it yourself!

**Comment by DaGnYMilleR** [comment]
> You can do it yourself!

Sorry, but I don't know any programming language(
If u will spend some time to teach me, I'll help u.
